// lks-frontend-vue/src/pages/Leaderboard.vue
<template>
  <div class="min-h-screen bg-gray-900 text-white p-6">
    <div class="flex justify-between mb-4">
      <h1 class="text-2xl font-bold">Leaderboard</h1>
      <button @click="logout" class="bg-red-600 px-4 py-2 rounded">
        Logout
      </button>
      <button
        @click="goBack"
        class="px-6 py-2 bg-blue-600 hover:bg-blue-700 rounded text-lg"
      >
        Back
      </button>
    </div>

    <ul>
      <li v-for="(u, i) in data" :key="i" class="bg-gray-800 p-2 mb-2 rounded">
        {{ i + 1 }}. {{ u.username }} — {{ u.score }}
      </li>
    </ul>
  </div>
</template>

<script setup>
import axios from "axios";
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const data = ref([]);

onMounted(async () => {
  if (!localStorage.getItem("token")) router.push("/");

  const res = await axios.get("http://127.0.0.1:8000/api/leaderboard", {
    headers: {
      Authorization: `Bearer ${localStorage.getItem("token")}`,
    },
  });

  data.value = res.data;
});

const goBack = () => {
  window.location.href = "/"
}

const logout = async () => {
  try {
    await axios.post(
      "http://127.0.0.1:8000/api/logout",
      {},
      {
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      },
    );
  } finally {
    localStorage.removeItem("token");
    router.push("/");
  }
};
</script>

// game-react-fronntend/src/pages/Leaderboard.jsx
import { useEffect, useState } from "react";
import axios from "axios";

export default function Leaderboard() {
  const [leaderboard, setLeaderboard] = useState([]);
  const [myRank, setMyRank] = useState(null);
  const [loading, setLoading] = useState(true);
  const API_URL = "http://127.0.0.1:8000/api";

  useEffect(() => {
    const token = localStorage.getItem("token");

    const fetchLeaderboard = async () => {
      try {
        const leaderboardRes = await axios.get(
          `${API_URL}/leaderboard`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/json",
            },
          }
        );

        setLeaderboard(leaderboardRes.data);

        const myRankRes = await axios.get(
          `${API_URL}/my-rank`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: "application/json",
            },
          }
        );

        setMyRank(myRankRes.data);
      } catch (err) {
        console.error(err.response?.data || err);
      } finally {
        setLoading(false);
      }
    };

    fetchLeaderboard();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center text-white">
        Loading leaderboard...
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-900 text-white p-6">
      <h1 className="text-3xl font-bold text-center mb-6">🏆 Leaderboard</h1>

      {myRank && (
        <div className="bg-yellow-600/20 border border-yellow-500 p-4 rounded-lg mb-6 text-center">
          <p className="text-lg font-semibold">🎯 Rank Kamu</p>
          <p>
            #{myRank.rank} — {myRank.username} ({myRank.score} pts)
          </p>
        </div>
      )}

      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-gray-800">
              <th className="p-3 text-left">Rank</th>
              <th className="p-3 text-left">Player</th>
              <th className="p-3 text-left">Score</th>
            </tr>
          </thead>
          <tbody>
            {leaderboard.map((item, index) => (
              <tr
                key={item.id}
                className={`border-b border-gray-700 ${
                  myRank?.user_id === item.user_id
                    ? "bg-green-700/30 font-bold"
                    : ""
                }`}
              >
                <td className="p-3">#{index + 1}</td>
                <td className="p-3">{item.username}</td>
                <td className="p-3">{item.score}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
